#!/bin/bash

case "$1" in
    "c37")
        llm -m claude-3.7-sonnet
        ;;
    "c35")
        llm -m claude-3.5-sonnet
        ;;
    "o1")
        llm  -m o1
        ;;
    "4o")
        llm -m 4o
        ;;
    "o1m")
        llm -m o1-mini
        ;;
    "o3m")
        llm  -m o3-mini
        ;;
    *)
        echo "Usage: $0 {claude37|claude35|o1|4o|o1-mini|o3-mini}"
        ;;
esac
