SELECT
       DATE(START_TIME) AS QUERY_DATE,
       COUNT(DISTINCT QUERY_HASH) AS UNIQUE_QUERIES,
       COUNT(QUERY_TEXT) AS TOTAL_QUERIES,
       TO_VARCHAR(MIN(CONVERT_TIMEZONE('UTC', START_TIME)) ,'yyyy-mm-dd
   hh24:mi:ss') AS EARLIEST_UTC,
       TO_VARCHAR(MAX(CONVERT_TIMEZONE('UTC', START_TIME)) ,'yyyy-mm-dd
   hh24:mi:ss') AS LATEST_UTC,
       COUNT(DISTINCT DATE(START_TIME)) AS DAY_COUNT,
       ARRAY_UNIQUE_AGG(JSON_EXTRACT_PATH_TEXT(s.CLIENT_ENVIRONMENT,
   'APPLICATION')) AS ARR_APP_NAME,
       COUNT(DISTINCT JSON_EXTRACT_PATH_TEXT(s.CLIENT_ENVIRONMENT, 'APPLICATION'))
   AS UNIQ_APP_NAME,
       ARRAY_UNIQUE_AGG(JSON_EXTRACT_PATH_TEXT(s.CLIENT_ENVIRONMENT, 'OS')) AS
   ARR_OP_SYS,
       COUNT(DISTINCT JSON_EXTRACT_PATH_TEXT(s.CLIENT_ENVIRONMENT, 'OS')) AS
   UNIQ_OS,
       ARRAY_UNIQUE_AGG(l.CLIENT_IP)AS ARR_IP,
       COUNT( DISTINCT l.CLIENT_IP) AS UNIQ_IP,
   FROM snowflake.account_usage.query_history q
       JOIN snowflake.account_usage.sessions s ON s.session_id = q.session_id
       JOIN snowflake.account_usage.login_history l ON l.EVENT_ID =
   s.LOGIN_EVENT_ID
   GROUP BY
QUERY_DATE
